export const mockProducts = [
  {
    _id: '1',
    name: 'T-shirt with Tape Details',
    description: 'A classic t-shirt with tape details on the sleeves. Perfect for casual and streetwear looks.',
    price: 120,
    stock: 50,
    images: ['/products/tshirt1.jpg'],
    category: 'T-shirts',
    paymentType: 'money',
    pointsPrice: 1200,
    isOnSale: false,
    discountPercentage: 0,
    salePrice: 120,
    rating: 4.5,
  },
  {
    _id: '2',
    name: 'Skinny Fit Jeans',
    description: 'Slim-fitting jeans with a modern wash. Comfortable stretch denim in a versatile blue shade.',
    price: 260,
    stock: 30,
    images: ['/products/jeans1.jpg'],
    category: 'Jeans',
    paymentType: 'hybrid',
    pointsPrice: 2400,
    isOnSale: true,
    discountPercentage: 20,
    salePrice: 208,
    rating: 3.5,
  },
  {
    _id: '3',
    name: 'Checkered Shirt',
    description: 'A timeless checkered shirt perfect for layering. Made with soft cotton for all-day comfort.',
    price: 180,
    stock: 40,
    images: ['/products/shirt1.jpg'],
    category: 'Shirts',
    paymentType: 'money',
    pointsPrice: 1800,
    isOnSale: false,
    discountPercentage: 0,
    salePrice: 180,
    rating: 4.5,
  },
  {
    _id: '4',
    name: 'Sleeve Striped T-shirt',
    description: 'A bold striped t-shirt with contrasting sleeves. Eye-catching design for everyday wear.',
    price: 160,
    stock: 25,
    images: ['/products/tshirt2.jpg'],
    category: 'T-shirts',
    paymentType: 'money',
    pointsPrice: 1300,
    isOnSale: true,
    discountPercentage: 30,
    salePrice: 112,
    rating: 4.5,
  },
  {
    _id: '5',
    name: 'Vertical Striped Shirt',
    description: 'Elegant vertical striped shirt for a polished look. Ideal for both casual Fridays and weekend outings.',
    price: 232,
    stock: 20,
    images: ['/products/shirt2.jpg'],
    category: 'Shirts',
    paymentType: 'hybrid',
    pointsPrice: 2120,
    isOnSale: true,
    discountPercentage: 20,
    salePrice: 185.6,
    rating: 5.0,
  },
  {
    _id: '6',
    name: 'Courage Graphic T-shirt',
    description: 'Express yourself with this unique graphic tee. Premium print quality that lasts wash after wash.',
    price: 145,
    stock: 35,
    images: ['/products/tshirt3.jpg'],
    category: 'T-shirts',
    paymentType: 'money',
    pointsPrice: 1450,
    isOnSale: false,
    discountPercentage: 0,
    salePrice: 145,
    rating: 4.0,
  },
  {
    _id: '7',
    name: 'Loose Fit Bermuda Shorts',
    description: 'Comfortable bermuda shorts with a relaxed fit. Perfect for warm weather and active lifestyles.',
    price: 80,
    stock: 45,
    images: ['/products/shorts1.jpg'],
    category: 'Shorts',
    paymentType: 'points',
    pointsPrice: 800,
    isOnSale: false,
    discountPercentage: 0,
    salePrice: 80,
    rating: 3.0,
  },
  {
    _id: '8',
    name: 'Faded Skinny Jeans',
    description: 'Modern faded skinny jeans with a lived-in look. Stretch fabric ensures maximum comfort and mobility.',
    price: 210,
    stock: 28,
    images: ['/products/jeans2.jpg'],
    category: 'Jeans',
    paymentType: 'money',
    pointsPrice: 2100,
    isOnSale: false,
    discountPercentage: 0,
    salePrice: 210,
    rating: 4.5,
  },
  {
    _id: '9',
    name: 'Polo with Contrast Trims',
    description: 'A premium polo shirt featuring contrast trims. Sophisticated and sporty style combined.',
    price: 242,
    stock: 15,
    images: ['/products/polo1.jpg'],
    category: 'T-shirts',
    paymentType: 'hybrid',
    pointsPrice: 2120,
    isOnSale: true,
    discountPercentage: 20,
    salePrice: 193.6,
    rating: 4.0,
  },
  {
    _id: '10',
    name: 'Gradient Graphic T-shirt',
    description: 'Stand out with this gradient graphic tee. Vibrant colors that pop on a premium cotton base.',
    price: 145,
    stock: 60,
    images: ['/products/tshirt4.jpg'],
    category: 'T-shirts',
    paymentType: 'money',
    pointsPrice: 1450,
    isOnSale: false,
    discountPercentage: 0,
    salePrice: 145,
    rating: 3.5,
  },
  {
    _id: '11',
    name: 'Polo with Tipping Details',
    description: 'Classic polo with refined tipping details on collar and cuffs. A wardrobe essential for every man.',
    price: 180,
    stock: 22,
    images: ['/products/polo2.jpg'],
    category: 'T-shirts',
    paymentType: 'money',
    pointsPrice: 1800,
    isOnSale: false,
    discountPercentage: 0,
    salePrice: 180,
    rating: 4.5,
  },
  {
    _id: '12',
    name: 'Black Striped T-shirt',
    description: 'A sleek black t-shirt with contrasting white stripes. Minimalist design with maximum impact.',
    price: 150,
    stock: 38,
    images: ['/products/tshirt5.jpg'],
    category: 'T-shirts',
    paymentType: 'money',
    pointsPrice: 1500,
    isOnSale: true,
    discountPercentage: 30,
    salePrice: 105,
    rating: 5.0,
  },
];
